- name: expense backend configuration
  hosts: backend
  become: yes
  tasks:
  - name: disable nodejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enalbe nodejs module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: installed
