- name: install my sql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql
      state: removed  # state must be one of: absent, installed, latest, present, removed