- name: install my sql server
  hosts: mysql
  become: yes
  vars:
    mysql_password: ExpenseApp@1
  tasks:
  - name: install python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed  # state must be one of: absent, installed, latest, present, removed

  - name: start mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: set root password
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_password }}"
      login_host: mysql.dawscloud.tech
      register: mysql_info

  - name: print mysql_info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"
